version: '2.2'

volumes:
  orderer2.gmp.com:
  peer2.hospital.com:
  peer3.hospital.com:
  peer2.patient.com:
  peer3.patient.com:

networks:
  fabric_network:
    name: medical_network

services:
  # order service nodes
  orderer2.gmp.com:
    container_name: orderer2.gmp.com
    image: hyperledger/fabric-orderer:2.4.2
    environment:
      - GODEBUG=netdns=go
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/config/genesis.block # inject genesis block
      - ORDERER_GENERAL_LOCALMSPID=GMPMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/orderer/msp # about certificate
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/orderer/tls/ca.crt]
    command: orderer
    ports:
      - "7050:7050"
    volumes: # mount certificate files generated by "cryptogen" and "configtxgen"
      - ./config/genesis.block:/etc/hyperledger/config/genesis.block
      - ./crypto-config/ordererOrganizations/gmp.com/orderers/orderer2.gmp.com/:/etc/hyperledger/orderer
      - orderer2.gmp.com:/var/hyperledger/production/orderer
    networks:
      - fabric_network

  #  hospital organization——peer2 node
  peer2.hospital.com:
    extends:
      file: docker-compose-base.yaml
      service: peer-base
    container_name: peer2.hospital.com
    environment:
      - CORE_PEER_ID=peer2.hospital.com
      - CORE_PEER_LOCALMSPID=HospitalMSP
      - CORE_PEER_ADDRESS=peer2.hospital.com:7051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peer/tls/ca.crt
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.hospital.com:7051
    ports:
      - "7051:7051" # grpc service port
      - "7053:7053" # eventhub port
    volumes:
      - ./crypto-config/peerOrganizations/hospital.com/peers/peer2.hospital.com:/etc/hyperledger/peer
      - peer2.hospital.com:/var/hyperledger/production
    depends_on:
      - orderer2.gmp.com
      - couchdb0

  #  hospital organization——peer3 node
  peer3.hospital.com:
    extends:
      file: docker-compose-base.yaml
      service: peer-base
    container_name: peer3.hospital.com
    environment:
      - CORE_PEER_ID=peer3.hospital.com
      - CORE_PEER_LOCALMSPID=HospitalMSP
      - CORE_PEER_ADDRESS=peer3.hospital.com:7051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peer/tls/ca.crt
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer3.hospital.com:7051
    ports:
      - "17051:7051"
      - "17053:7053"
    volumes:
      - ./crypto-config/peerOrganizations/hospital.com/peers/peer3.hospital.com:/etc/hyperledger/peer
      - peer3.hospital.com:/var/hyperledger/production
    depends_on:
      - orderer2.gmp.com
      - couchdb0

  #  patient organization——peer2 node
  peer2.patient.com:
    extends:
      file: docker-compose-base.yaml
      service: peer-base
    container_name: peer2.patient.com
    environment:
      - CORE_PEER_ID=peer2.patient.com
      - CORE_PEER_LOCALMSPID=PatientMSP
      - CORE_PEER_ADDRESS=peer2.patient.com:7051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peer/tls/ca.crt
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.patient.com:7051
    ports:
      - "27051:7051"
      - "27053:7053"
    volumes:
      - ./crypto-config/peerOrganizations/patient.com/peers/peer2.patient.com:/etc/hyperledger/peer
      - peer2.patient.com:/var/hyperledger/production
    depends_on:
      - orderer2.gmp.com
      - couchdb0

  #  patient organization——peer3 node
  peer3.patient.com:
    extends:
      file: docker-compose-base.yaml
      service: peer-base
    container_name: peer3.patient.com
    environment:
      - CORE_PEER_ID=peer3.patient.com
      - CORE_PEER_LOCALMSPID=PatientMSP
      - CORE_PEER_ADDRESS=peer3.patient.com:7051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peer/tls/ca.crt
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer3.patient.com:7051
    ports:
      - "37051:7051"
      - "37053:7053"
    volumes:
      - ./crypto-config/peerOrganizations/patient.com/peers/peer3.patient.com:/etc/hyperledger/peer
      - peer3.patient.com:/var/hyperledger/production
    depends_on:
      - orderer2.gmp.com
      - couchdb0