version: '2.2'

services:
  peer-base: # peer public service
    image: hyperledger/fabric-peer:2.4.2
    environment:
      - GODEBUG=netdns=go
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_PEER=info
      - CORE_CHAINCODE_LOGGING_LEVEL=INFO
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp # msp certificate (note certificate)
      - CORE_LEDGER_STATE_STATEDATABASE=goleveldb # stated database storage engine(or CouchDB)
      #- CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      #- CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=medical_network # docker network
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    networks:
      - fabric_network